# .goreleaser.yml
version: 2
project_name: monomaker
builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=plugin
    goos:
      - linux
    goarch:
      - amd64

  - id: windows-amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=plugin
    goos:
      - windows
    goarch:
      - amd64

  - id: darwin-native
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=plugin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.dll{{ else if eq .Os \"darwin\" }}.vst{{ else }}.so{{ end }}"
