version: 2

project_name: monomaker
builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -tags=plugin
    goos:
      - "{{ .Env.GOOS }}"
    goarch:
      - "{{ .Env.GOARCH }}"

archives:
  - formats:
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}l{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
